export const SELECT_MEAL = 'SELECT_MEAL';
export const SELECT_PEOPLE = 'SELECT_PEOPLE';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const SELECT_FOOD='SELECT_FOOD';
export const RESET_VALUE = 'RESET_VALUE';
export const DELETE_FOOD = 'DELETE_FOOD';